import type { DeckData, MetricKey, Milestone, ScheduledPost } from "./types";

export const METRIC_LABEL: Record<MetricKey, string> = {
  followers: "Followers",
  impressions24h: "24h impressions",
  impressions7d: "7d impressions",
  engagement: "Engagement rate",
  revenueMonth: "Monthly revenue",
  postsWeek: "Posts this week",
  streak: "Check-in streak",
};

/**
 * Target markers, not achievements — every `hitAt` starts null. A fresh
 * account hasn't hit any of these yet; the deck marks them hit itself once
 * live (or hand-logged) numbers actually cross the target.
 */
export const seedMilestones: Milestone[] = [
  {
    id: "ms-10k",
    title: "10K event horizon",
    blurb: "Ten thousand souls in the wake. Gravity well established.",
    metric: "followers",
    target: 10_000,
    hitAt: null,
    winLine: "First gravity well. They can see the deck from here.",
  },
  {
    id: "ms-50k",
    title: "50K constellation",
    blurb: "A private constellation of people who chose you on purpose.",
    metric: "followers",
    target: 50_000,
    hitAt: null,
    winLine: "Fifty thousand. That's not a crowd. That's a nation-state of taste.",
  },
  {
    id: "ms-100k-day",
    title: "Hundred-thousand day",
    blurb: "A single rotation with six figures of eyes. Unholy. Delicious.",
    metric: "impressions24h",
    target: 100_000,
    hitAt: null,
    winLine: "The day-side of Earth just subscribed to the bit.",
  },
  {
    id: "ms-1m-week",
    title: "Million-week burn",
    blurb: "Seven days. A million impressions. Leave the atmosphere.",
    metric: "impressions7d",
    target: 1_000_000,
    hitAt: null,
    winLine: "A million looks in a week. The void filed a noise complaint.",
  },
  {
    id: "ms-8eng",
    title: "Eight-percent weather",
    blurb: "Engagement that has its own pressure system.",
    metric: "engagement",
    target: 8,
    hitAt: null,
    winLine: "Eight percent. That's not a rate. That's a climate.",
  },
  {
    id: "ms-1k-month",
    title: "First thousand-dollar moon",
    blurb: "The treasury finally has a moon of its own.",
    metric: "revenueMonth",
    target: 1_000,
    hitAt: null,
    winLine: "Payday has a zip code now. It's in orbit.",
  },
  {
    id: "ms-5k-month",
    title: "Five-grand apogee",
    blurb: "A month that pays like a job you can't be fired from.",
    metric: "revenueMonth",
    target: 5_000,
    hitAt: null,
    winLine: "Five thousand in a cycle. The rent just became folklore.",
  },
  {
    id: "ms-14streak",
    title: "Fortnight of fire",
    blurb: "Fourteen consecutive docks. Ritual is a superpower.",
    metric: "streak",
    target: 14,
    hitAt: null,
    winLine: "Two weeks without a miss. That's how dynasties start: on a Tuesday.",
  },
  {
    id: "ms-30streak",
    title: "Thirty-day halo",
    blurb: "A full lunar cycle of showing up. Mythic. Slightly unhinged.",
    metric: "streak",
    target: 30,
    hitAt: null,
    winLine: "Thirty days. The moon is jealous of your calendar.",
  },
  {
    id: "ms-12posts",
    title: "Dozen launches",
    blurb: "Twelve transmissions this week. The feed is a launchpad.",
    metric: "postsWeek",
    target: 12,
    hitAt: null,
    winLine: "A dozen ships left the bay. One of them will own the sky.",
  },
];

/** No demo posts pre-staged — the queue starts empty until you add or sync real ones. */
export const seedContentQueue: ScheduledPost[] = [];

export const seedDeck: DeckData = {
  commanderName: "Commander",
  stats: {
    followers: 0,
    impressions24h: 0,
    impressions7d: 0,
    engagement: 0,
    revenueX: 0,
    revenueTips: 0,
    revenueOther: 0,
    postsWeek: 0,
    sparkline: [],
  },
  milestones: seedMilestones,
  revenueLogs: [],
  notes: [],
  posts: [],
  verticals: [
    {
      id: "threads",
      name: "Threads",
      callsign: "Helix",
      planet: "/brand/planet-threads.jpg",
      exploration: 0,
      posts: 0,
      brief: "Short burns. High spin. The slingshot lane.",
    },
    {
      id: "visuals",
      name: "Visuals",
      callsign: "Solaris",
      planet: "/brand/planet-visuals.jpg",
      exploration: 0,
      posts: 0,
      brief: "Stills that stop a thumb mid-orbit.",
    },
    {
      id: "longform",
      name: "Longform",
      callsign: "Nebula",
      planet: "/brand/planet-longform.jpg",
      exploration: 0,
      posts: 0,
      brief: "Deep-field essays. Slow, then sudden.",
    },
    {
      id: "collabs",
      name: "Collabs",
      callsign: "Twin Suns",
      planet: "/brand/planet-collabs.jpg",
      exploration: 0,
      posts: 0,
      brief: "Two gravity wells, one trajectory.",
    },
    {
      id: "live",
      name: "Livestreams",
      callsign: "Forge",
      planet: "/brand/planet-live.jpg",
      exploration: 0,
      posts: 0,
      brief: "Heat, voice, no take-backs. The furnace.",
    },
    {
      id: "labs",
      name: "Experiments",
      callsign: "Drift",
      planet: "/brand/planet-labs.jpg",
      exploration: 0,
      posts: 0,
      brief: "Unmapped. On purpose. That's the point.",
    },
  ],
  streak: {
    count: 0,
    lastCheckIn: null,
    todayMessage: null,
    todayKey: null,
  },
  contentQueue: seedContentQueue,
};
